### ISSUE TITLE
The 3rd Course Advanced Computer Vision

### ISSUE THREAD

**Issue by The-ML-Hero** [weeeBox/coursera-tensorflow#1]
Could you please upload the 3rd course pls reply as soon as possible

**Comment by weeeBox** [comment]
I haven't started it yet

**Comment by The-ML-Hero** [comment]
Could You Please Upload the Labs At Least Please! Please Reply As Soon As Possible

**Comment by weeeBox** [comment]
You can download the labs yourself: enroll in the course trial, download notebooks, and cancel the subscription. It's not great advice but would work in this case. Also if you can't afford the course - you can always apply for the financial aid program at Coursera and if you qualify - you would get the course for free.
